PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://example.org/onto-example.owl#>

#

SELECT distinct ?sc ?info_source ?plant_info ?FB
WHERE {

    ?sc a :Scenario;
        :has_info_source ?info_source.
    {?info_source :has_info ?plant_info.}
    UNION
    {?info_source :has_FB ?FB.}

}

